import test from 'node:test';
import assert from 'node:assert/strict';
import {createReplay,replayReceipt} from '../scripts/lib/ledger-replay.mjs';
import {nativeGenerateKey,nativeSign,nativeHash,nativeCanonical} from '../src/native-crypto.ts';
import {applyNativeTransaction} from '../src/native-core.ts';
const issuer=nativeGenerateKey(),payer=nativeGenerateKey(),attacker=nativeGenerateKey(),now=Date.now(),genesis={domain:'cinder.genesis.v1',chainId:'cinder-devnet-1',symbol:'CINDER',decimals:6,supplyAtoms:'1000000000000',allocation:'system:reserve',operatorPublicKey:issuer.publicKey,createdAt:new Date(now-1000).toISOString(),consensus:'single-operator-devnet'},signature=nativeSign(genesis,issuer.secretKey),hash=nativeHash(nativeCanonical(genesis));
function fixture(){const state=createReplay(genesis,signature,hash,issuer.publicKey);state.accounts[payer.address]={address:payer.address,publicKey:payer.publicKey,balanceAtoms:'0',nonce:0,claimedFaucet:false,createdAt:genesis.createdAt};const transaction={domain:'cinder.transaction.v1',chainId:genesis.chainId,sender:payer.address,nonce:1,validUntil:new Date(now+60000).toISOString(),maxDebitAtoms:'0',actions:[{type:'faucet'}]},t=applyNativeTransaction(state.accounts,transaction,now);return {state,transaction,postings:t.postings,result:t.result};}
function receipt(f,postings=f.postings,signer=payer){const checkpoint={domain:'cinder.checkpoint.v1',chainId:genesis.chainId,height:1,previousHash:hash,transactionHash:nativeHash(nativeCanonical(f.transaction)),postingsHash:nativeHash(nativeCanonical(postings)),resultHash:nativeHash(nativeCanonical(f.result)),timestamp:new Date(now).toISOString(),mode:'single-operator-devnet'};return {transaction:f.transaction,signature:nativeSign(f.transaction,signer.secretKey),postings,result:f.result,checkpoint,checkpointSignature:nativeSign(checkpoint,issuer.secretKey)};}
test('auditor independently reproduces authorized native state transitions',async()=>{const f=fixture();await replayReceipt(f.state,receipt(f),{[payer.address]:payer.publicKey});assert.equal(f.state.accounts[payer.address].balanceAtoms,'100000000');assert.equal(f.state.height,1);});
test('valid operator signature cannot authorize a substituted payer public key',async()=>{const f=fixture();await assert.rejects(replayReceipt(f.state,receipt(f,f.postings,attacker),{[payer.address]:attacker.publicKey}),/derive the claimed account/);});
test('zero-sum operator-signed postings still fail when they exceed payer-authorized rules',async()=>{const f=fixture(),forged=[{account:'system:reserve',deltaAtoms:'-200000000'},{account:payer.address,deltaAtoms:'200000000'}];await assert.rejects(replayReceipt(f.state,receipt(f,forged),{[payer.address]:payer.publicKey}),/exactly implement/);});
test('valid signature under a different checkpoint domain is not a native checkpoint',async()=>{const f=fixture(),r=receipt(f);r.checkpoint.domain='cinder.alternative.v1';r.checkpointSignature=nativeSign(r.checkpoint,issuer.secretKey);await assert.rejects(replayReceipt(f.state,r,{[payer.address]:payer.publicKey}));});
