import fs from 'node:fs/promises';
import path from 'node:path';
import {marked} from 'marked';
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const template=(title,content)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} — Cinder Rail</title><meta name="description" content="Cinder Rail: budgeted machine compute, signed receipts, explicit trust boundaries."><link rel="icon" href="/icon.svg"><link rel="stylesheet" href="/docs.css"></head><body><header><a href="/">◈ CINDER RAIL</a><nav><a href="/">Console</a><a href="/protocol">Protocol</a><a href="/developers">Developers</a></nav></header><main>${content}</main><footer>Experimental sandbox · Test credits have no monetary value · <a href="/privacy">Privacy</a></footer></body></html>`;
await fs.mkdir('public/docs',{recursive:true});
const files=(await fs.readdir('docs')).filter(f=>f.endsWith('.md'));
for(const f of files){const source=await fs.readFile(path.join('docs',f),'utf8');const title=source.match(/^# (.+)/m)?.[1]||f;await fs.writeFile(path.join('public/docs',f.replace('.md','.html')),template(title,marked.parse(source)));await fs.copyFile(path.join('docs',f),path.join('public/docs',f));}
const security=await fs.readFile('docs/security.md','utf8').catch(()=> '# Security\nThis experimental sandbox is not audited. No real funds are accepted.');
await fs.writeFile('public/security.html',template('Security',marked.parse(security)));
await fs.writeFile('public/privacy.html',template('Privacy',marked.parse('# Privacy\n\nCinder Rail is a public experimental compute service. No account, wallet connection, analytics tracker or advertising cookie is required.\n\nThe browser generates an agent signing key in memory. The private key remains in your browser and is lost on reload. The server stores your public key, temporary test-credit ledger, signed quotes, hashes, compute outputs and receipts for up to 24 hours. The private session token authorizes quotes and ledger reads. It stays in browser memory and is not included in exported receipts. Keep the token private.\n\nFor Llama inference, the text you submit is sent to Cloudflare Workers AI, running a Meta model. Do not submit secrets or sensitive personal information. Hash inputs are processed by the Worker and are not stored as plaintext in the session ledger. Outputs are retained temporarily so retries do not run paid compute again.\n\nThe service uses a daily salted hash of the connecting IP address to limit sandbox sessions. The application does not store raw IP addresses or enable request logging, although the hosting provider may process network data according to its own policies. Rate-limit records rotate daily.\n\nThe provider signs receipts with an operator-controlled key. Anyone who receives an exported receipt can read its fields. A signature proves the issuer and integrity, not that model execution was correct.\n\nTest credits have no cash value, cannot be transferred and expire with the session. There is no purchase, deposit, withdrawal or token sale.')));
await fs.writeFile('public/docs.css',`*{box-sizing:border-box}body{margin:0;background:#f5f3ec;color:#252820;font:16px/1.8 system-ui,sans-serif}header,footer{max-width:1100px;margin:auto;padding:28px;display:flex;justify-content:space-between;gap:20px}header>a{font-weight:800;letter-spacing:.12em}nav{display:flex;gap:20px}a{color:#a83a18;text-underline-offset:4px}header a{text-decoration:none}main{max-width:860px;margin:36px auto 100px;padding:0 24px}h1{font-size:clamp(32px,6vw,54px);line-height:1.12;letter-spacing:-.045em}h2{margin-top:2em;line-height:1.2}h3{line-height:1.3}pre{background:#20271f;color:#f5f3ec;padding:24px;overflow:auto;border-radius:12px}code{font-size:.88em}table{border-collapse:collapse;width:100%;display:block;overflow-x:auto}td,th{border-bottom:1px solid #ccc8bc;text-align:left;padding:12px;min-width:120px}blockquote{border-left:3px solid #dc592e;margin-left:0;padding-left:20px}footer{border-top:1px solid #ccc8bc;font-size:12px;display:block}@media(max-width:600px){header{flex-direction:column}nav{flex-wrap:wrap}main{margin-top:12px}}`);
await fs.writeFile('public/llms.txt',`# Cinder Rail\n\nExperimental HTTP 402 compute sandbox. No real payments or token.\n\n- [Console](/)\n- [Developer guide](/developers)\n- [API catalog](/api/catalog)\n- [Issuer public key](/api/key)\n- [Architecture](/docs/architecture.md)\n- [Security](/docs/security.md)\n\nProtocol is cinder-sandbox-v1, not x402 wire compatible. Denomination sandbox-microUSD is nonredeemable test accounting. Agent keys ECDSA P-256; provider receipt signatures certify provenance, not inference correctness.\n`);
await fs.mkdir('public/.well-known',{recursive:true});
await fs.writeFile('public/.well-known/cinder.json',JSON.stringify({name:'Cinder Rail',version:'0.1.0',protocol:'cinder-sandbox-v1',mode:'sandbox',catalog:'/api/catalog',issuerKey:'/api/key',openapi:'/openapi.json',documentation:'/developers',realPayments:false,x402Compatible:false},null,2));
await fs.writeFile('public/robots.txt','User-agent: *\nAllow: /\nDisallow: /api/sessions/\n');
console.log(`Built ${files.length} protocol documents, privacy, security and agent discovery files.`);
